desc: test

train:
  seed: 42
  num_epochs: 2000
  lr: 0.001
  patience: 200
  save_folder: './results/'
  device: 'cuda:0'
  log_interval: 10

model:
  name: 'MolPropModel'
  input_dim: 64
  hidden_dim: 64
  num_energies: 24
  num_heads: 8
  num_layers: 3
  dropout: 0.2
  return_repr: False


data:
  path: 'diffusion_coef_h2o.pickle'
  additional_features: None
  batch_size: 128
  replace: False
  logarithm: True

mixed:
  ckpt_path: 'results/checkpoints/'
  viscosity: 'MolPropModel_viscosity_fighting.pt'
  thermal_cond: 'MolPropModel_thermal_cond_fighting.pt'
  diffusion_coef: 'MolPropModel_diffusion_coef_fighting.pt'
  diffusion_coef_h2o: 'MolPropModel_diffusion_coef_h2o_fighting.pt'
  viscosityG: 'MolPropModel_viscosityG_fighting.pt'
  thermal_condG: 'MolPropModel_thermal_condG_fighting.pt'